#add_newline = true
format = ["username", "kubernetes", "directory", "git_branch", "git_status", "character"]

[username]
show_always = true

[directory]
truncation_length = 8
truncation_symbol = "â€¦/"
truncate_to_repo = false

[time]
disabled = false
#format = 'ğŸ•™[\[ $time \]]($style) '
#time_format = "%T"
#utc_time_offset = "-5"
#time_range = "10:00:00-14:00:00"

[docker_context]
disabled = false
#[git_status]
#conflicted = " ~ "
#ahead = " â‡¡ "
#behind = " â‡£ "
#staged=" + "
#diverged = " â‡• "
#untracked = " ? "
#stashed = " $ "
#modified = " ! "
#deleted = " ïš¿ "
#renamed = " âœ "
#unmerged = " â• "
